locations = [
    (0x10f, "Special Purpose Area [includes Bike Race & after Zeal Fall CS]"),
    (0x2, "Crono's Room"),
    (0x1, "Crono's Kitchen"),
    (0x5, "Millenial Fair"),
    (0x1b7, "Leene Square"),
    (0x8, "Telepod Exhibit"),
    (0x71, "Truce Canyon Portal"),
    (0x70, "Truce Canyon"),
    (0x1f1, "Middle Ages [OVERWORLD]"),
    (0x77, "Guardia Forest (Middle Ages)"),
    (0x78, "Guardia Throneroom (Middle Ages)"),
    (0x1d4, "Guardia Queen's Tower (Middle Ages)"),
    (0x7a, "Guardia Queen's Chamber (Middle Ages)"),
    (0x6c, "Lucca Explains Paradoxes"),
    (0x81, "Manoria Sanctuary"),
    (0x82, "Manoria Main Hall"),
    (0xc7, "Manoria Confinement"),
    (0x83, "Manoria Headquarters"),
    (0x84, "Manoria Royal Guard Hall"),
    (0xc6, "Manoria Command"),
    (0x13, "Guardia Forest (Present)"),
    (0x15, "Guardia Throneroom (Present)"),
    (0x1b, "Courtroom"),
    (0x1c, "Prison Catwalks"),
    (0x1d, "Prison Supervisor's Office"),
    (0x47, "Prison Cells"),
    (0x48, "Prison Stairwells"),
    (0x1e9, "Guardia Prison Tower"),
    (0x14, "Guardia Forest Dead End"),
    (0xd0, "Bangor Dome"),
    (0x1f2, "Future [OVERWORLD]"),
    (0xd4, "Lab 16 West"),
    (0xd5, "Lab 16 East"),
    (0xd6, "Arris Dome"),
    (0xd8, "Arris Dome Auxiliary Console"),
    (0xdd, "Arris Dome Rafters"),
    (0xdb, "Arris Dome Guardian Chamber"),
    (0x158, "Arris Dome Food Locker"),
    (0xd7, "Arris Dome Infestation"),
    (0xd9, "Arris Dome Lower Commons"),
    (0xda, "Arris Dome Command Central"),
    (0xdf, "Lab 32 West Entrance"),
    (0xe1, "Lab 32 East Entrance"),
    (0xe2, "Proto Dome"),
    (0xe4, "Factory Ruins Entrance"),
    (0xe5, "Factory Ruins Auxiliary Console"),
    (0xe6, "Factory Ruins Security Center"),
    (0xeb, "Factory Ruins Power Core"),
    (0xe3, "Proto Dome Portal"),
    (0x1d0, "End of Time"),
    (0x1d1, "Spekkio"),
    (0x24, "Medina Portal Medina Residence"),
    (0x21, "Medina Elder's House 1F"),
    (0x22, "Medina Elder's House 2F"),
    (0x30, "Heckran Cave Entrance"),
    (0x31, "H.Cave Underground River"),
    (0x2f, "Heckran Cave Passageways"),
    (0x87, "Zenan Bridge (Middle Ages)"),
    (0x7b, "Guardia Kitchen (Middle Ages)"),
    (0x8b, "Sandorino Market"),
    (0x91, "Denadoro Entrance"),
    (0x8e, "Denadoro South Face"),
    (0x92, "Denadoro Lower East Face"),
    (0x8f, "Denadoro Cave of the Masamune Exterior"),
    (0x93, "Denadoro Upper East Face"),
    (0x96, "Denadoro Gauntlet"),
    (0x90, "Denadoro North Face"),
    (0x94, "Denadoro Mountain Vista"),
    (0x95, "Denadoro West Face"),
    (0x97, "Denadoro Cave of the Masamune"),
    (0x9d, "Porre Market (Middle Ages)"),
    (0x98, "Tata's House 1F"),
    (0x9a, "Porre Elder's House [JERKY]"),
    (0x8c, "Cursed Woods"),
    (0x8d, "Frog's Burrow"),
    (0x28, "Melchior's Kitchen"),
    (0x110, "Mystic Mtn Portal"),
    (0x111, "Mystic Mtn Base"),
    (0x112, "Mystic Mtn Gulch"),
    (0x1f3, "Prehistoric [OVERWORLD]"),
    (0x113, "Chief's Hut"),
    (0x118, "Ioka Meeting Site (Party)"),
    (0x117, "Ioka Meeting Site"),
    (0x11a, "Forest Maze"),
    (0x11b, "Reptite Lair Entrance"),
    (0x11c, "Reptite Lair 1F"),
    (0x11d, "Reptite Lair Weevil Burrows B1"),
    (0x11e, "Reptite Lair Weevil Burrows B2"),
    (0x11f, "Reptite Lair Commons"),
    (0x120, "Reptite Lair Tunnel"),
    (0x121, "Reptite Lair Azala's Room"),
    (0x29, "Melchior's Workshop"),
    (0xce, "Guardia Throneroom Cyrus's Final Mission"),
    (0xcc, "Guardia Forest Frog King Battle"),
    (0xcd, "Denadoro Cyrus's Last Battle"),
    (0xa3, "Magic Cave Exterior"),
    (0xa4, "Magic Cave Interior"),
    (0xa5, "Castle Magus Exterior"),
    (0xa6, "Castle Magus Entrance"),
    (0x1d5, "Castle Magus Corridor of Combat"),
    (0xa9, "Castle Magus Throne of Strength"),
    (0xab, "Castle Magus Hall of Deceit"),
    (0x7d, "Castle Magus Doppleganger Corridor"),
    (0xad, "Castle Magus Throne of Magic"),
    (0xaa, "Castle Magus Hall of Aggression"),
    (0xa7, "Castle Magus Chamber of Guillotines"),
    (0xb0, "Castle Magus Lower Battlements"),
    (0xa8, "Castle Magus Chamber of Pits"),
    (0x1be, "Castle Magus Upper Battlements"),
    (0xaf, "Castle Magus Hall of Apprehension"),
    (0x1d6, "Castle Magus Hall of Ambush"),
    (0xae, "Castle Magus Throne of Defense"),
    (0x1bf, "Castle Magus Grand Stairway"),
    (0xac, "Castle Magus Inner Sanctum"),
    (0x124, "Laruba Ruins"),
    (0x125, "Dactyl Nest, Lower"),
    (0x126, "Dactyl Nest, Upper"),
    (0x127, "Dactyl Nest Summit"),
    (0x12b, "Tyrano Lair Entrance"),
    (0x1ae, "Tyrano Lair Main Cell"),
    (0x12e, "Tyrano Lair Antechambers"),
    (0x12a, "Tyrano Lair Exterior"),
    (0x131, "Tyrano Lair Room of Vertigo"),
    (0x12f, "Tyrano Lair Storage"),
    (0x130, "Tyrano Lair Nizbel's Room"),
    (0x12c, "Tyrano Lair Throneroom"),
    (0x12d, "Tyrano Lair Keep"),
    (0x105, "Prehistoric Canyon"),
    (0x133, "Lair Ruins Portal"),
    (0x15f, "Dark Ages Portal"),
    (0x1f4, "Dark Ages [OVERWORLD]"),
    (0x151, "Skyway? (TBD)"),
    (0x161, "Land Bridge (TBD)"),
    (0x1f5, "Kingdom of Zeal [OVERWORLD]"),
    (0x150, "Land Bridge (TBD)"),
    (0x162, "Skyway (TBD)"),
    (0x164, "Skyway (TBD)"),
    (0x160, "Land Bridge (TBD)"),
    (0x185, "Zeal Teleporters"),
    (0x191, "Zeal Palace"),
    (0x192, "Zeal Palace Hallway"),
    (0x148, "Zeal Palace Schala's Room"),
    (0x149, "Zeal Palace Regal Hall"),
    (0x14a, "Zeal Palace Corridor to the Mammon Machine"),
    (0x14b, "Zeal Palace Hall of the Mammon Machine"),
    (0x14c, "Zeal Palace Zeal Throneroom"),
    (0x14d, "Zeal Palace Hall of the Mammon Machine (Night)"),
    (0xf1, "Keeper's Dome [cutscene & real]"),
    (0x2a, "Forest Ruins Pyramid"),
    (0x74, "Truce Inn 1F (Middle Ages)"),
    (0x75, "Truce Inn 2F (Middle Ages)"),
    (0x9f, "Sunken Desert Entrance"),
    (0xa0, "Sunken Desert Parasytes"),
    (0xa1, "Sunken Desert Devourer"),
    (0x9e, "Fiona's Villa"),
    (0xc, "Truce Inn (Present)"),
    (0x1e6, "Guardia King's Tower (Present)"),
    (0x39, "Fiona's Shrine"),
    (0x1b4, "Fiona's Forest Campfire"),
    (0x53, "Fiona's Forest Recriminations Lucca's Gate"),
    (0xa, "Lucca's Room"),
    (0x3, "Lucca's Kitchen"),
    (0x4, "Lucca's Workshop"),
    (0x1d2, "Apocalypse Lavos [Headless map]"),
    (0x1f7, "1999 World Map [OVERWORLD]"),
    (0xe0, "Lab 32"),
    (0xec, "Sewer Access B1"),
    (0xed, "Sewer Access B2"),
    (0xf2, "Keeper's Dome Corridor"),
    (0xf3, "Keeper's Dome Hanger"),
    (0x1b0, "Flying Epoch"),
    (0x182, "Algetty Entrance"),
    (0x17c, "Algetty"),
    (0x184, "The Beast's Nest"),
    (0x18a, "Mt. Woe Middle Eastern Face"),
    (0x188, "Mt. Woe Western Face"),
    (0x189, "Mt. Woe Lower Eastern Face"),
    (0x18b, "Mt. Woe Upper Eastern Face"),
    (0x18d, "Mt. Woe Summit"),
    (0x17e, "Algetty Elder's Grotto"),
    (0x14e, "Zeal Palace Zeal Throneroom (Night)"),
    (0x194, "Ocean Palace Entrance"),
    (0x19f, "Ocean Palace Throneroom [Cutscene & real]"),
    (0x195, "Ocean Palace Piazza"),
    (0x196, "Ocean Palace Side Rooms [incl. Scout Skips]"),
    (0x197, "Ocean Palace Forward Area"),
    (0x198, "Ocean Palace B3 Landing"),
    (0x199, "Ocean Palace Grand Stairwell"),
    (0x19a, "Ocean Palace B20 Landing"),
    (0x19b, "Ocean Palace Southern Access Lift"),
    (0x1a0, "Ocean Palace (TBD) [ELEVATOR]"),
    (0x1a2, "Ocean Palace Western Access Lift"),
    (0x19c, "Ocean Palace Security Pool"),
    (0x19d, "Ocean Palace Security Esplanade"),
    (0x19e, "Ocean Palace Regal Antechamber [Golemtwins]"),
    (0x1a7, "Ocean Palace Time Freeze [Crono dies]"),
    (0x1ee, "Paradise Lost"),
    (0x165, "Kajar [real & Fall-of-Zeal scene]"),
    (0x1ed, "Algetty Tsunami"),
    (0x1a9, "Last Village Empty Hut"),
    (0x1f6, "Last Village (12000 World Map) [OVERWORLD]"),
    (0x1aa, "Last Village Shop"),
    (0x1a8, "Last Village Commons"),
    (0x173, "Blackbird Cell"),
    (0x16c, "Blackbird Right Port"),
    (0x16e, "Blackbird Overhead"),
    (0x178, "Blackbird Ducts"),
    (0x171, "Blackbird Forward Halls"),
    (0x176, "Blackbird Inventory"),
    (0x1de, "Blackbird Wing Access"),
    (0x16b, "Blackbird Left Wing"),
    (0x16f, "Blackbird Hanger"),
    (0x179, "Reborn Epoch [Dalton fight]"),
    (0x1e1, "Death of the Blackbird"),
    (0x1d8, "Apocalypse Epoch (Last Village)"),
    (0x1ac, "North Cape"),
    (0x1dd, "(Epoch) Emergence of the Black Omen"),
    (0xbc, "Choras Cafe"),
    (0x3e, "Choras Inn (Present)"),
    (0x3d, "Choras Carpenter's Residence"),
    (0xba, "Choras Carpenter's Residence 1F (Middle Ages)"),
    (0x41, "Northern Ruins Entrance (600 & 1000)"),
    (0x42, "Northern Ruins Basement Corridor (600 & 1000)"),
    (0x49, "Northern Ruins Hero's Grave (600 & 1000)"),
    (0x1d9, "End of Time Epoch"),
    (0xfb, "Sun Palace"),
    (0x147, "Sunkeep (Prehistoric)"),
    (0x40, "Sun Keep (Present)"),
    (0x32, "Porre Mayor's Manor 1F (Present)"),
    (0xff, "Sun Keep (Future)"),
    (0xc3, "Giant's Claw Entrance [incl. Lizards]"),
    (0x129, "Giant's Claw Lair Throneroom"),
    (0x6e, "Ancient Tyrano Lair Traps"),
    (0xc4, "Giant's Claw Caverns"),
    (0x6f, "Ancient Tyrano Lair Nizbel's Room [escape ladder]"),
    (0x6d, "Ancient Tyrano Lair"),
    (0x128, "Giant's Claw Lair Entrance"),
    (0xc5, "Giant's Claw Last Tyranno"),
    (0xf8, "Geno Dome Entrance"),
    (0xf9, "Geno Dome Conveyor Entrance"),
    (0x7e, "Geno Dome Main Conveyor"),
    (0xfa, "Geno Dome Conveyor Exit"),
    (0x100, "Geno Dome Labs"),
    (0x7f, "Geno Dome Elevator [both]"),
    (0x10c, "Geno Dome Mainframe (Atropos)"),
    (0x80, "Geno Dome Long Corridor"),
    (0x10b, "Geno Dome Robot Elevator Access"),
    (0x1e8, "Guardia Lawgiver's Tower"),
    (0x1b9, "Courtroom Lobby"),
    (0x1b6, "Courtroom King's Trial"),
    (0x1a, "Guardia Basement"),
    (0x1b8, "Guardia Rear Storage [Prism]"),
    (0x6, "Gato's Exhibit"),
    (0x1b2, "Bekkler's Lab"),
    (0xf4, "Death Peak Entrance"),
    (0xf5, "Death Peak South Face"),
    (0xf6, "Death Peak Southeast Face"),
    (0x108, "Death Peak Cave [1st Spawn]"),
    (0x107, "Death Peak Lower North Face"),
    (0xf7, "Death Peak Northeast Face [2nd Spawn]"),
    (0x106, "Death Peak Upper North Face"),
    (0x104, "Death Peak Northwest Face [Egg Slide]"),
    (0x1ef, "Death Peak Guardian Spawn [3rd Spawn]"),
    (0x109, "Death Peak Summit"),
    (0x1ad, "Death Peak Summit [Hug scene]"),
    (0xb1, "Ozzie's Fort Entrance"),
    (0xb7, "Ozzie's Fort Throne of Impertinence [Flea]"),
    (0xb2, "Ozzie's Fort Hall of Disregard"),
    (0xb8, "Ozzie's Fort Throne of Ineptitude [Slash]"),
    (0xb3, "Ozzie's Fort Chamber of Kitchen Knives"),
    (0xb4, "Ozzie's Fort Last Stand [big fight]"),
    (0xb5, "Ozzie's Fort Throne of Incompetence"),
    (0x1c1, "Black Omen Entrance"),
    (0x134, "Black Omen 1F Entrance [Megamutan]"),
    (0x135, "Black Omen 1F Walkway [Goon]"),
    (0x136, "Black Omen 1F Defense Corridor [Panel]"),
    (0x137, "Black Omen 1F Stairway [Eyeball1]"),
    (0x138, "Black Omen 3F Walkway [Metalmute]"),
    (0x61, "Black Omen 3F Teleporter [entries: 1st,3rd]"),
    (0x62, "Black Omen 45F Teleporter [exits: 2nd,4th]"),
    (0x63, "Black Omen Platform [all 4 landings]"),
    (0x64, "Black Omen Platform Shaft [downward]"),
    (0x139, "Black Omen Auxilary Command [Trap Floors 1]"),
    (0x13a, "Black Omen (TBD) Trap Floors 2"),
    (0x13b, "Black Omen (TBD) Nu Shop"),
    (0x13c, "Black Omen (TBD) Tubster (lower/upper)"),
    (0x13d, "Black Omen (TBD) Cybot/Rumin"),
    (0x13e, "Black Omen (TBD) Eyeball 2"),
    (0x13f, "Black Omen (TBD) Tubster"),
    (0x140, "Black Omen (TBD) teleport"),
    (0x141, "Black Omen (TBD) teleport"),
    (0x142, "Black Omen (TBD) Aliens"),
    (0x143, "Black Omen (TBD) Gigamutant"),
    (0x65, "Black Omen Platform Shaft (upward)"),
    (0x144, "Black Omen (TBD) Synchrite fight"),
    (0x145, "Black Omen (TBD) Teramutant"),
    (0x146, "Black Omen (TBD) walkway to Spawn"),
    (0x60, "Black Omen Lavos Spawn"),
    (0x1c2, "Black Omen Omega Defense"),
    (0x1c3, "Black Omen Seat of Agelessness [Zeal1]"),
    (0x1a6, "Time Distortion Mammon Machine"),
    (0x6b, "Black Omen Celestial Gate [Zeal fight]"),
    (0x1d3, "Lavos Fight"),
    (0x15b, "Prison Catwalks (Battle with Lavos)"),
    (0x15a, "Arris Dome Guardian Chamber (Battle with Lavos)"),
    (0x15c, "Heckran Cave (Battle with Lavos)"),
    (0x15d, "Zenan Bridge (Battle with Lavos)"),
    (0x15e, "Cave of the Masamune (Battle with Lavos)"),
    (0x1c8, "Reptite Lair (Battle with Lavos)"),
    (0x1c9, "Castle Magus Inner Sanctum (Battle with Lavos)"),
    (0x1ca, "Tyrano Lair Keep (Battle with Lavos)"),
    (0x1cb, "Mt. Woe Summit (Battle with Lavos)"),
    (0x1da, "Lavos Tunnel"),
    (0x1db, "Lavos Core"),
    (0x1df, "Tesseract"),
    (0x52, "Ending Selector [NewGame+ unlocks upon 052 loading]"),
    (0x7, "Prehistoric Exhibit"),
    (0x9, "Lara's Room"),
    (0xb, "Ending Selector (not used?)"),
    (0xd, "Truce Mayor's Manor 1F"),
    (0xe, "Truce Mayor's Manor 2F"),
    (0xf, "Truce Single Woman Residence"),
    (0x10, "Truce Happy Screaming Couple Residence"),
    (0x11, "Truce Market (Present)"),
    (0x12, "Truce Ticket Office"),
    (0x16, "King's Chamber (Present)"),
    (0x17, "Queen's Chamber (Present)"),
    (0x18, "Guardia Kitchen (Present)"),
    (0x19, "Guardia Barracks (Present)"),
    (0x1e, "Prison Torture Storage Room"),
    (0x1f, "Medina Square"),
    (0x20, "Zenan Bridge (Present)"),
    (0x23, "Medina Inn"),
    (0x25, "Ending: Legendary Hero"),
    (0x26, "Guardia Throneroom (Ending)"),
    (0x27, "Medina Market"),
    (0x2b, "Cursed Woods (Ending)"),
    (0x2c, "Leene Square (Future)"),
    (0x2d, "Denadoro Mtn Vista (Ending)"),
    (0x2e, "Castle Magus Throne (Ending)"),
    (0x33, "Porre Mayor's Manor 2F (Present)"),
    (0x34, "Porre Residence (Present)"),
    (0x35, "Snail Stop"),
    (0x36, "Porre Market (Present)"),
    (0x37, "Porre Inn (Present)"),
    (0x38, "Porre Ticket Office"),
    (0x3a, "Choras Mayor's Manor 1F"),
    (0x3b, "Choras Mayor's Manor 2F"),
    (0x3c, "Castle Magus Hall (Ending)"),
    (0x3f, "West Cape Toma's Grave"),
    (0x43, "Northern Ruins Landing (Present)"),
    (0x44, "Northern Ruins Antechamber (Present)"),
    (0x45, "Northern Ruins Vestibule (Present)"),
    (0x46, "Northern Ruins Back Room (Present)"),
    (0x4a, "Unknown"),
    (0x4b, "Prison Exterior"),
    (0x4c, "Unknown (Lavos Spawn)"),
    (0x4d, "Unknown (Lavos Spawn)"),
    (0x4e, "Unknown (Lavos Spawn)"),
    (0x4f, "Guardia Throneroom (Ending: Moonlight Parade)"),
    (0x50, "Millenial Fair (Ending: Moonlight Parade)"),
    (0x51, "Leene Square (Ending: Moonlight Parade)"),
    (0x54, "End of Time (Ending: Moonlight Parade)"),
    (0x55, "Telepod Exhibit (Ending: Moonlight Parade)"),
    (0x56, "Death Peak Summit (Ending: Moonlight Parade)"),
    (0x57, "Manoria Sanctuary (Ending: The Successor of Guardia)"),
    (0x58, "The End"),
    (0x59, "Zenan Bridge (Ending: Moonlight Parade)"),
    (0x5a, "Prison Catwalks (Ending: Moonlight Parade)"),
    (0x5b, "Ending: People of the Times (Part 1)"),
    (0x5c, "Ending: People of the Times (Part 2)"),
    (0x5d, "Ending: People of the Times (Part 3)"),
    (0x5e, "Ending: People of the Times (Part 4)"),
    (0x5f, "Ending: People of the Times (Part 5)"),
    (0x66, "Black Omen Celestial Gate (no map)"),
    (0x67, "Black Omen Celestial Gate (no map)"),
    (0x68, "Black Omen Celestial Gate (no map)"),
    (0x69, "Black Omen Celestial Gate (no map)"),
    (0x6a, "Black Omen Celestial Gate (no map)"),
    (0x72, "Truce Couple's Residence (Middle Ages)"),
    (0x73, "Truce Smithy's Residence"),
    (0x76, "Truce Market (Middle Ages)"),
    (0x79, "Guardia King's Chamber (Middle Ages)"),
    (0x7c, "Guardia Barracks (Middle Ages)"),
    (0x85, "Zenan Bridge (Wrecked)"),
    (0x86, "Zenan Bridge (Middle Ages, no map)"),
    (0x88, "Sandorino Pervert Residence"),
    (0x89, "Sandorino Elder's House"),
    (0x8a, "Sandorino Inn"),
    (0x99, "Tata's House 2F"),
    (0x9b, "Porre Cafe (Middle Ages)"),
    (0x9c, "Porre Inn (Middle Ages)"),
    (0xa2, "Ozzie's Fort Entrance (no map)"),
    (0xb6, "Ozzie's Fort Throne of Impertinence (wrong map)"),
    (0xb9, "Choras Old Couple Residence (Middle Ages)"),
    (0xbb, "Choras Carpenter's Residence 2F (Middle Ages)"),
    (0xbd, "Choras Inn (Middle Ages)"),
    (0xbe, "Choras Market (Middle Ages)"),
    (0xbf, "Sun Keep (Middle Ages)"),
    (0xc0, "(empty map)"),
    (0xc1, "(empty map)"),
    (0xc2, "(empty map)"),
    (0xc8, "Manoria Shrine Antechamber"),
    (0xc9, "Manoria Storage"),
    (0xca, "Manoria Kitchen"),
    (0xcb, "Manoria Shrine"),
    (0xcf, "Schala's Room (no map)"),
    (0xd1, "Bangor Dome Sealed Room"),
    (0xd2, "Trann Dome"),
    (0xd3, "Trann Dome Sealed Room"),
    (0xdc, "Arris Dome Sealed Room"),
    (0xde, "Reptite Lair 2F (escape ladder)"),
    (0xe7, "Factory Ruins Crane Room"),
    (0xe8, "Factory Ruins Infestation"),
    (0xe9, "Factory Ruins Crane Control Room"),
    (0xea, "Factory Ruins Information Archive (XABY)"),
    (0xee, "Ending: Dream Team (no map) (TBD)"),
    (0xef, "Ending: A Slide Show?"),
    (0xf0, "Ending: Goodnight"),
    (0xfc, "Millenial Fair (Ending: Dino Age)"),
    (0xfd, "Sun Keep (Last Village)"),
    (0xfe, "Skill Tutorial"),
    (0x101, "Geno Dome Storage (south,locked)"),
    (0x102, "Geno Dome Robot Hub (north)"),
    (0x103, "Factory Ruins xData Corex (Robot Storage!)"),
    (0x10a, "Ending: Dream Team (no map) (TBD)"),
    (0x10d, "Geno Dome Waste Disposal (soylent room)"),
    (0x10e, "Leene's Square (Ending: Dino Age)"),
    (0x114, "Ioka Southwestern Hut"),
    (0x115, "Ioka Trading Post"),
    (0x116, "Ioka Sweet Water Hut"),
    (0x119, "Forest Maze Entrance (no entry)"),
    (0x122, "Reptite Lair Access Shaft (escape ladder)"),
    (0x123, "Hunting Range"),
    (0x132, "Debug Room?"),
    (0x14f, "Enhasa (wrong map)"),
    (0x152, "Present Age Home Room (Ending: The Dream Project)"),
    (0x153, "Prehistoric Age Jungle (Ending: The Dream Project)"),
    (0x154, "Dark Age Ocean Palace Room (Ending: The Dream Project)"),
    (0x155, "Present Age Jail Cell (Ending: The Dream Project)"),
    (0x156, "Dark Age Earthbound Room (Ending: The Dream Project)"),
    (0x157, "Present Age Northern Ruins Room (Ending: The Dream Project)"),
    (0x159, "Lucca's Workshop (Ending: The Oath)"),
    (0x163, "Enhasa"),
    (0x166, "Kajar Study"),
    (0x167, "Kajar Belthasar's Private Room"),
    (0x168, "Kajar Magic Lab"),
    (0x169, "Zeal Palace Belthasar's Private Room"),
    (0x16a, "Blackbird Scaffolding"),
    (0x16d, "Blackbird Left Port"),
    (0x170, "Blackbird Rear Halls"),
    (0x172, "Blackbird Treasury"),
    (0x174, "Blackbird Barracks"),
    (0x175, "Blackbird Armory 3"),
    (0x177, "Blackbird Lounge"),
    (0x17a, "Future Age Room (Ending: The Dream Project)"),
    (0x17b, "End of Time (Ending: The Dream Project)"),
    (0x17d, "Algetty Inn"),
    (0x17f, "Algetty Commoner Grotto"),
    (0x180, "Algetty Shop"),
    (0x181, "Algetty Tsunami (wrong map)"),
    (0x183, "The Beast's Nest (wrong map)"),
    (0x186, "Prehistoric Hut (Ending: The Dream Project)"),
    (0x187, "Castle Magus Room (Ending: The Dream Project)"),
    (0x18c, "Mt. Woe Summit (wrong map)"),
    (0x18e, "Leene Square (Ending: What the Prophet Seeks)"),
    (0x18f, "Crono's Kitchen (Ending: What the Prophet Seeks)"),
    (0x190, "The End (Ending: Multiple?)"),
    (0x193, "Zeal Palace Study"),
    (0x1a1, "Ocean Palace Eastern Access Lift"),
    (0x1a3, "Ocean Palace Time Freeze (wrong map)"),
    (0x1a4, "Ocean Palace Time Freeze (wrong map)"),
    (0x1a5, "Ocean Palace Time Freeze (wrong map)"),
    (0x1ab, "Last Village Residence"),
    (0x1af, "Title Screen (wrong map)"),
    (0x1b3, "Magic Cave Exterior (all visits after the cutscene)"),
    (0x1b5, "Factory Ruins (TBD) Fight gauntlet"),
    (0x1ba, "Blackbird Access Shaft"),
    (0x1bb, "Blackbird Armory 2"),
    (0x1bc, "Blackbird Armory 1"),
    (0x1bd, "Blackbird Storage"),
    (0x1c0, "(Bad Event Data Packet)"),
    (0x1c4, "(Bad Event Data Packet)"),
    (0x1c5, "(Bad Event Data Packet)"),
    (0x1c6, "(Bad Event Data Packet)"),
    (0x1c7, "(Bad Event Data Packet)"),
    (0x1cc, "Credits (TBD)"),
    (0x1cd, "(Empty Data)"),
    (0x1ce, "(Empty Data)"),
    (0x1cf, "(Empty Data)"),
    (0x1d7, "Castle Magus Dungeon"),
    (0x1dc, "Truce Dome"),
    (0x1e0, "Guardia King's Tower (Middle Ages)"),
    (0x1e2, "Blackbird (no exits)"),
    (0x1e3, "Blackbird (no exits)"),
    (0x1e4, "Blackbird (no exits)"),
    (0x1e5, "Blackbird (no exits)"),
    (0x1e7, "Guardia Queen's Tower (Present)"),
    (0x1ea, "Ancient Tyrano Lair Room of Vertigo (Giant's Claw Teleport Room)"),
    (0x1eb, "(empty map)"),
    (0x1ec, "(empty map)"),
    (0x1f8, "(empty map)"),
    (0x1f9, "(empty map)"),
    (0x1fa, "(empty map)"),
    (0x1fb, "(empty map)"),
    (0x1fc, "(empty map)"),
    (0x1fd, "(empty map)"),
    (0x1fe, "(empty map)"),
    (0x1ff, "(empty map)")
    ]